# SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

@ENTRIES = (
   { name => "ant-1.7.0-ziputil-patched" },
   { name => "ant-tar-patched" },
   { name => "ical4j-0.9.16-patched" },
   { name => "junixsocket" },
   { name => "zm-ajax" },
   { name => "zm-admin-ajax" },
   { name => "zm-amavis" },
   { name => "zm-certificate-manager-admin-zimlet" },
   { name => "zm-certificate-manager-store" },
   { name => "zm-charset" },
   { name => "zm-clam-scanner-store" },
   { name => "zm-core-utils" },
   { name => "zm-db-conf" },
   { name => "zm-freshclam" },
   { name => "zm-helptooltip-zimlet" },
   { name => "zm-jetty-conf" },
   { name => "zm-jython" },
   { name => "zm-launcher" },
   { name => "zm-ldap-utilities" },
   { name => "zm-mailbox" },
   { name => "zm-mta" },
   { name => "zm-nginx-lookup-store" },
   { name => "zm-openid-consumer-store" },
   { name => "zm-pkg-tool" },
   { name => "zm-postfix" },
   { name => "zm-proxy-config-admin-zimlet" },
   { name => "zm-taglib" },
   { name => "zm-viewmail-admin-zimlet" },
   { name => "zm-zcs" },
   { name => "zm-zimlets" },
   { name => "zm-oauth-social" },
   { name => "zm-gql" },
);
